version: "3.8"

services:
  postgres:
    image: postgis/postgis
    # containter_name: geo-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ~/geo-volumes/postgresql:/var/lib/posgresql/data

volumes:
  postgres:
    driver: local