version: "3.8"

services:
  scylla-node-1:
    container_name: scylla-node-1
    image: "scylladb/scylla"
    hostname: scylla-node-1
    command: --smp 1 --memory 750M
    # ports:
    #   - "9042:9042"
    # volumes:
    #   - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
    restart: always
    # networks:
    #   vnet:

  scylla-node-2:
    container_name: scylla-node-2
    image: "scylladb/scylla"
    hostname: scylla-node-2
    command: --seeds=scylla-node-1 --smp 1 --memory 750M
    # ports:
    #   - "9043:9042"
    # volumes:
    #   - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
    restart: always
    depends_on:
      - scylla-node-1
    # networks:
    #   vnet:

  scylla-node-3:
    container_name: scylla-node-3
    image: "scylladb/scylla"
    hostname: scylla-node-3
    command: --seeds=scylla-node-1 --smp 1 --memory 750M
    # ports:
    #   - "9044:9042"
    # volumes:
    #   - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
    restart: always
    depends_on:
      - scylla-node-1
      - scylla-node-2
    # networks:
    #   vnet:

# networks:
#   vnet:
#     driver: bridge
