version: "3.8"

services:
  postgres:
    container_name: idk_postgres
    image: postgis/postgis
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ~/geo-volumes/postgresql:/var/lib/posgresql/data

  # backend:
  #   container_name: idk_backend
  #   depends_on:
  #     - postgres
  #   build: .
  #   ports:
  #     - "${PORT}:8000"
  #   restart: always

# volumes:
#   postgres:
#     driver: localversion: "3.8"

